"""init

Revision ID: 13f56439764f
Revises: 
Create Date: 2020-05-08 08:36:39.452148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f56439764f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('osu_uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('osu_uid')
    )
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('song', sa.Unicode(), nullable=False),
    sa.Column('link', sa.Unicode(), nullable=True),
    sa.Column('mapset_id', sa.Integer(), nullable=True),
    sa.Column('mapper', sa.Unicode(), nullable=False),
    sa.Column('reason', sa.Unicode(), nullable=True),
    sa.Column('archive', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['requester_id'], ['users.osu_uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_requested_at'), 'requests', ['requested_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_requested_at'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
