"""empty message

Revision ID: 516e7b5669ce
Revises: ffb438f701fb
Create Date: 2020-06-25 09:48:49.178932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516e7b5669ce'
down_revision = 'ffb438f701fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rules', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('rules')

    # ### end Alembic commands ###
